version: '3'

services:

  cloudera:
    image: cloudera/quickstart:latest
    container_name: Cloudera
    hostname: quickstart.cloudera
    privileged: true
#    command: /bin/bash
    command: /usr/bin/docker-quickstart 
#    command: "/home/cloudera/clouder-manager --express"
    stdin_open: true # keep process stdin open awaiting connect (keeps cloudera running)
    tty: true # specifies that stdin should be a terminal
    mem_limit: "30g"
    mem_reservation: "20g"
    cpus: "16"
    ports:
      - 80:80       # quickstart
      - 8020:8020   # HDFS 
      - 2222:2222       # SSH
      - 7180:7180   # Cloudera Manager
      - 8888:8888   # Hue
      - 11000:11000 # Oozie
      - 50070:50070 # HDFS Rest Namenode
      - 50075:50075 # HDFS Rest Datanode
      - 2181:2181   # Zookeeper
      - 8088:8088   # YARN Resource Manager
      - 19888:19888 # MapReduce Job History
      - 50030:50030 # MapReduce Job Tracker
      - 8983:8983   # Solr
      - 16000:16000 # Sqoop Metastore
      - 8042:8042   # YARN Node Manager
      - 60010:60010 # HBase Master
      - 60030:60030 # HBase Region
      - 9090:9090   # HBase Thrift
      - 8080:8080   # HBase Rest
      - 7077:7077   # Spark Master

    volumes: 
      - ./var_lib:/var/lib
      - ./data:/home/cloudera/DEV01

#      - ./data/tmp:/tmp
#      - ./data/hdfs:/var/lib/hadoop-hdfs/cache